---
- hosts: khala_manager:khala_worker
  roles:
    - role: geerlingguy.docker
      become: yes
      ansible_become_password: "{{password}}"
  - tasks:
    - name: set docker log limit
      shell: echo -e "{\n  \"log-driver\":\"json-file\",\n  "log-opts": {\"max-size\":\"200m\", \"max-file\":\"3\"}\n}\n" > /etc/docker/daemon.json
    - name: restart docker service
      service:
        name: docker
        state: restarted
- hosts: localhost
  connection: local
  tasks:
    - name: init docker swarm
      shell: "docker swarm init"
      ignore_errors: true
    - name: init docker overlay network
      shell: "docker network create -d overlay --attachable khala"
      ignore_errors: true
- hosts: khala_manager
  tasks:
    - name: get docker swarm token
      local_action: shell docker swarm join-token manager
      register: token
    - name: join docker swarm
      shell: "{{token.stdout.split('\n')[2] | trim}}"
      ignore_errors: true
- hosts: khala_worker
  tasks:
    - name: get docker swarm token
      local_action: shell docker swarm join-token worker
      register: token
    - name: join docker swarm
      shell: "{{token.stdout.split('\n')[2] | trim}}"
      ignore_errors: true
